language: java

before_install:
  - mysql -e 'CREATE DATABASE shop;'

test:
  adapter: mysql
  database: shop
  username: root
  encoding: utf8

install:
  -

notifications:
  email:
    recipients:
      - zhouwentao16@gmail.com

after_success:
  - coveralls